name: Label_issues
on:
  issues:
    types:
      - reopened
      - opened
      - assigned
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
       - run: |
            gh issue edit "$NUMBER" --add-label "$LABEL1" --add-label "$LABEL2" --add-label "$LABEL3"
            env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GH_REPO: ${{ github.repository }}
            NUMBER: ${{ github.event.issue.number }}
            LABEL1: "good first issue"
            LABEL2: "Test"
            LABEL3: "Testing"