name: Label issues
on:
  issues:
    types:
      - reopened
      - opened

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Set up GitHub CLI
        run: |
          gh auth setup-git
          gh auth status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add label to issue
        run: gh issue edit ${{ github.event.issue.number }} --add-label triage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
