name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
      - assigned
      - unassigned

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label the issue
        run: gh issue edit ${{ github.event.issue.number }} --add-label "triage,good first issue,Test,bug,documentation,help wanted,invalid"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
