name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
      - assigned
      - unassigned
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh issue edit "$NUMBER" --add-label "$TRIGGERED_LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          TRIGGERED_LABELS: ${{ github.event.label.name }}